version: '{build}'

clone_folder: C:\gopath\src\github.com\bearmini\go-acl

environment:
  GOPATH: C:\gopath

install:
  - go version
  - go env
  - go get -t -v ./...

build: off

test_script:
  - go test -v ./...
